config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get   'users/info'                        => 'users#info'
  get   'users/login'                       => 'users#login_form'
  post  'users/login'                       => 'users#login'
  get   'users/logout'                      => 'users#logout'
  get   'users/register'                    => 'users#register_form'
  post  'users/register'                    => 'users#register'
  post  'users/edit/:user_id'               => 'users#edit'

  get   'products'                          => 'products#receipts'
  get   'products/detail/:product_id'       => 'products#detail' , as: 'products_detail'
  get   'products/newproduct'               => 'products#newproduct'
  get   'products/search'                   => 'products#search'
  post  'products/create'                   => 'products#create'

  get   'about'                             => 'welcome#about'
  get   'contact'                           => 'welcome#contact'
  post  'contact'                           => 'welcome#sendcontact'
  get   'blog'                              => 'welcome#blog'
  get   'blogdetail'                        => 'welcome#blogdetail'
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_many :comments

  mount_uploader :photo, ProductPhotoUploader
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	include BCrypt

	has_many :products
	has_many :comments


	def password
		@password ||= Password.new(encrypted_password)
	end

	def password=(new_password)
		@password = Password.create(new_password)
		self.encrypted_password = @password
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	end

	def show
	end

	def destroy
	end

	def update
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
	end

	def show
	end

	def destroy
	end

	def update
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :check_login, only: [:create, :newproduct]

	def index
	end

	def detail
		if Product.exists?(id: params[:product_id])
			@product = Product.find(params[:product_id])
		else
			render json: {error: "dont have product"}
		end
	end

	def category
	end

	def receipts
		@products = Product.order(id: :desc)
	end

	def search
	end

	def newproduct
		@categorys = Category.all
	end

	def create
		@product = Product.new(product_params)
		@product.photo = params[:product][:photo]
		@product.user_id = session[:user]["id"]
		if @product.save
			redirect_to products_detail_path(product_id: @product.id)
		else
			redirect_to products_newreceipts_path
		end
	end

	private
		def product_params
			params.require(:product).permit(:title, :description, :status, :quantity, :category_id, :price )
		end

		def check_login
			if !session[:user]
				redirect_to users_login_path
			end
		end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

	def create
	end

	def show
	end

	def destroy
	end

	def update
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :check_login, only: [:info, :timeline, :edit]

	def info
		@user = User.find(session[:user]["id"])
		@products = @user.products
	end

	def timeline
	end

	def login_form
	end

	def login
		if User.exists?(email: params[:user][:email])
			@user = User.find_by(email: params[:user][:email])
			if @user.password == params[:user][:password]
				session[:user] = @user
				redirect_to users_info_path
			else
				redirect_to users_login_path
			end
		else
			redirect_to users_login_path
		end
	end

	def logout
		session.delete(:user)
		redirect_to users_login_path
	end

	def register_form
	end

	def register
		if params[:user][:password] == params[:user][:confirm_password]
			if User.exists?(email: params[:user][:email]) || validate_email(params[:user][:email])
				redirect_to users_register_path
			else
				@user = User.new(user_params)
				@user.password = params[:user][:password]
				if @user.save
					redirect_to users_login_path
				else
					redirect_to users_register_path
				end
			end
		else
			redirect_to users_register_path
		end
	end

	def edit
		@user = User.find(session[:user]["id"])
		@user.name = params[:user][:name]
		@user.address = params[:user][:address]
		@user.phone = params[:user][:phone]
		@user.avatar = params[:user][:avatar]
		if @user.save
			redirect_to users_info_path
		else
			render head 401
		end
	end

	private
		def check_login
			if !session[:user]
				redirect_to users_login_path
			end
		end

		def user_params
			params.require(:user).permit(:name, :email)
		end

		def validate_email(email)
			email !~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@product_lasteds = Product.order(id: :desc).limit(6)
	end

	def sendcontact
		name		= params[:name]
		email		= params[:email]
		phone		= params[:phone]
		comments	= params[:comments]

		UserContact.contact(name, email, phone, comments).deliver_now
		return head :ok
	end

	def contact

	end

	def blog
	end

	def blogdetail
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<!-- Mirrored from www.themeenergy.com/themes/html/social-chef/index.html by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 17 Apr 2015 04:33:05 GMT -->
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta name="keywords" content="SocialChef - Social Recipe HTML Template" />
	<meta name="description" content="SocialChef - Social Recipe HTML Template">
	<meta name="author" content="themeenergy.com">
	
	<title>SocialChef</title>
	
	<link rel="stylesheet" href="/css/style.css" />
	<link rel="stylesheet" href="/css/animate.css" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800" rel="stylesheet">
	<link rel="shortcut icon" href="//images/favicon.ico" />

	<script src="/js/jquery-1.11.1.min.js"></script>
	<script src="/js/jquery.uniform.min.js"></script>
	<script src="/js/wow.min.js"></script>
	<script src="/js/jquery.slicknav.min.js"></script>
	<script src="/js/scripts.js"></script>
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
</head>
<% if current_page?('/') %>
<body class="home">
<%else%>
<body>
<%end%>
	<!--header-->
	<header class="head" role="banner">
		<!--wrap-->
		<div class="wrap clearfix">
			<%= link_to(root_path, title: 'SocialChef', class: 'logo') do %><img src="/images/ico/logo.png" alt="SocialChef logo" /><%end%>
			<nav class="main-nav" role="navigation" id="menu">
				<ul>
					<li class="current-menu-item"><%= link_to(root_path, title: 'Home') do %><span>Home</span><%end%></li>
					<li><%= link_to(products_path, title: 'Recipes') do %><span>Recipes</span><%end%>
						<ul>
							<li><%= link_to "Receipt 2", products_path %></li>
							<li><%= link_to "Receipt", products_path %></li>
						</ul>
					</li>
					<li><%= link_to(blog_path, title: 'Blog') do %><span>Blog</span><%end%>
						<ul>
							<li><%= link_to(blogdetail_path, title: 'Blog post') do %><span>Blog post</span><%end%></li>
						</ul>
					</li>
					<li><a href="#" title="Pages"><span>Pages</span></a>
						<ul>
							<li><a href="left_sidebar.html" title="Left sidebar page">Left sidebar page</a></li>
							<li><a href="right_sidebar.html" title="Right sidebar page">Right sidebar page</a></li>
							<li><a href="two_sidebars.html" title="Both sidebars page">Both sidebars page</a></li>
							<li><a href="full_width.html" title="Full width page">Full width page</a></li>
							<li><a href="login.html" title="Login page">Login page</a></li><li><a href="register.html" title="Register page">Register page</a></li>
							<li><a href="error404.html" title="Error page">Error page</a></li>
						</ul>
					</li>
					<li><a href="#" title="Features"><span>Features</span></a>
						<ul>
							<li><a href="animations.html" title="Animations">Animations</a></li>
							<li><a href="grid.html" title="Grid">Grid</a></li>
							<li><a href="shortcodes.html" title="Shortcodes">Shortcodes</a></li>
							<li><a href="pricing.html" title="Pricing tables">Pricing tables</a></li>
						</ul>
					</li>
					<li><%= link_to(contact_path, title: 'Contact') do %><span>Contact</span><%end%></li>
					<li><a href="https://themeforest.net/item/socialchef-social-recipe-html-template/8568727?ref=themeenergy" title="Buy now"><span>Buy now</span></a></li>
				</ul>
			</nav>
			
			<nav class="user-nav" role="navigation">
				<ul>
					<li class="light">
						<%= link_to(products_search_path, title: 'Search for recipes') do %><i class="ico i-search"></i> <span>Search for recipes</span><%end%>
					</li>
					<li class="medium">
						<%= link_to(users_info_path, title: 'My account') do %><i class="ico i-account"></i> <span>My account</span><%end%>
					</li>
					<li class="dark">
						<%= link_to(products_newproduct_path, title: 'Submit a recipe') do %><i class="ico i-submitrecipe"></i> <span>Submit a recipe</span><%end%>
					</li>
				</ul>
			</nav>
		</div>
		<!--//wrap-->
	</header>
	<!--//header-->
		<%= yield %>
	<!--main-->

	<!--//call to action-->
	
	<!--footer-->
	<footer class="foot" role="contentinfo">
		<div class="wrap clearfix">
			<div class="row">
				<article class="one-half">
					<h5>About SocialChef Community</h5>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci.</p>
				</article>
				<article class="one-fourth">
					<h5>Need help?</h5>
					<p>Contact us via phone or email</p>
					<p><em>T:</em>  +1 555 555 555<br /><em>E:</em>  <a href="#">socialchef@email.com</a></p>
				</article>
				<article class="one-fourth">
					<h5>Follow us</h5>
					<ul class="social">
						<li class="facebook"><a href="#" title="facebook">facebook</a></li>
						<li class="youtube"><a href="#" title="youtube">youtube</a></li>
						<li class="rss"><a href="#" title="rss">rss</a></li>
						<li class="gplus"><a href="#" title="gplus">google plus</a></li>
						<li class="linkedin"><a href="#" title="linkedin">linkedin</a></li>
						<li class="twitter"><a href="#" title="twitter">twitter</a></li>
						<li class="pinterest"><a href="#" title="pinterest">pinterest</a></li>
						<li class="vimeo"><a href="#" title="vimeo">vimeo</a></li>
					</ul>
				</article>
				
				<div class="bottom">
					<p class="copy">Copyright 2014 SocialChef. All rights reserved</p>
					
					<nav class="foot-nav">
						<ul>
							<li><a href="index.html" title="Home">Home</a></li>
							<li><a href="recipes.html" title="Recipes">Recipes</a></li>
							<li><a href="blog.html" title="Blog">Blog</a></li>
							<li><a href="contact.html" title="Contact">Contact</a></li>    
							<li><a href="find_recipe.html" title="Search for recipes">Search for recipes</a></li>
							<li><a href="login.html" title="Login">Login</a></li>	<li><a href="register.html" title="Register">Register</a></li>		
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</footer>
	<!--//footer-->
	
	<!--preloader-->
	<div class="preloader">
		<div class="spinner"></div>
	</div>
	<!--//preloader-->
	
	
	<% if current_page?('/') %>
		<script>
		window.dynamicNumbersBound = false;
		var wow = new WOW();
		WOW.prototype.show = function(box) {
			wow.applyStyle(box);
			if (typeof box.parentNode !== 'undefined' && hasClass(box.parentNode, 'dynamic-numbers') && !window.dynamicNumbersBound) {
				bindDynamicNumbers();
				window.dynamicNumbersBound = true;
			}
			return box.className = "" + box.className + " " + wow.config.animateClass;
		};
		wow.init();
		
		function hasClass(element, cls) {
			return (' ' + element.className + ' ').indexOf(' ' + cls + ' ') > -1;
		}
		
		function bindDynamicNumbers() {
			$('.dynamic-number').each(function() {				
				var startNumber = $(this).text();
				var endNumber = $(this).data('dnumber');
				var dynamicNumberControl = $(this);
				
				$({numberValue: startNumber}).animate({numberValue: endNumber}, {
					duration: 4000,
					easing: 'swing',
					step: function() { 
						$(dynamicNumberControl).text(Math.ceil(this.numberValue)); 
					}
				});
			});	
		}
		
	</script>
	<%else%>
	<script>new WOW().init();</script>
	<%end%>
</body>

<!-- Mirrored from www.themeenergy.com/themes/html/social-chef/index.html by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 17 Apr 2015 04:34:11 GMT -->
</html>

app/views/products/detail.html.erb
<main class="main" role="main">
		<!--wrap-->
		<div class="wrap clearfix">
			<!--breadcrumbs-->
			<nav class="breadcrumbs">
				<ul>
					<li><a href="index.html" title="Home">Home</a></li>
					<li><a href="#" title="Recipes">Recipes</a></li>
					<li><a href="recipes.html" title="Cocktails">Deserts</a></li>
					<li>Recipe</li>
				</ul>
			</nav>
			<!--//breadcrumbs-->
			
			<!--row-->
			<div class="row">
				<header class="s-title wow fadeInLeft">
					<h1><%= @product.title %></h1>
				</header>
				<!--content-->
				<section class="content three-fourth">
					<!--recipe-->
						<div class="recipe">
							<div class="row">
								<!--two-third-->
								<article class="two-third wow fadeInLeft">
									<div class="image"><a href="#"><img src="<%= @product.photo_url %>" alt="" height="100%" width="100%"/></a></div>
									<div class="intro"><p><%= @product.description %></p></div>
									<div class="instructions">
										<ol>
											<li>Heat oven to 160C/140C fan/gas 3 and line a 12-hole muffin tin with cases. Gently melt the butter, chocolate, sugar and 100ml hot water together in a large saucepan, stirring occasionally, then set aside to cool a little while you weigh the other ingredients.</li>
											<li>Stir the eggs and vanilla into the chocolate mixture. Put the flour into a large mixing bowl, then stir in the chocolate mixture until smooth. Spoon into cases until just over three-quarters full (you may have a little mixture leftover), then set aside for 5 mins before putting on a low shelf in the oven and baking for 20-22 mins. Leave to cool.</li>
											<li>For the icing, melt the chocolate in a heatproof bowl over a pan of barely simmering water. Once melted, turn off the heat, stir in the double cream and sift in the icing sugar. When spreadable, top each cake with some and decorate with your favourite sprinkles and sweets.</li>
										</ol>
									</div>
								</article>
								<!--//two-third-->

								<!--one-third-->
								<article class="one-third wow fadeInDown">
									<dl class="basic">
										<dt>Price</dt>
										<dd><%= @product.price %></dd>
										<dt>Quantity</dt>
										<dd><%= @product.quantity %></dd>
										<dt>Category</dt>
										<dd><%= @product.category.title %></dd>
									</dl>

									<dl class="user">
										<dt>Category</dt>
										<dd>Deserts</dd>
										<dt>Posted by</dt>
										<dd>NoPu Nguyen</dd>
										<dt>Phone</dt>
										<dd>0975667043</dd>
										<dt>Address</dt>
										<dd>Ho Chi Minh, Thu Duc</dd>
										<dt>Email</dt>
										<dd>nopunguyen@gmail.com</dd>
									</dl>

									<dl class="ingredients">
										<dt>300g</dt>
										<dd>Self-raising flour</dd>
										<dt>200g</dt>
										<dd>Butter</dd>
										<dt>200g</dt>
										<dd>Plain chocolate</dd>
										<dt>2</dt>
										<dd>Eggs</dd>
										<dt>1 tbsp</dt>
										<dd>Vanilla extract</dd>
										<dt>200 g</dt>
										<dd>Brown sugar</dd>
										<dt>100 ml</dt>
										<dd>Double cream</dd>
										<dt>handful</dt>
										<dd>Sprinkles</dd>
									</dl>
								</article>
								<!--//one-third-->
							</div>
						</div>
						<!--//recipe-->

						<!--comments-->
						<div class="comments wow fadeInUp" id="comments">
							<h2>5 comments </h2>
							<ol class="comment-list">
								<!--comment-->
								<li class="comment depth-1">
									<div class="avatar"><a href="my_profile.html"><img src="/images/avatar1.jpg" alt="" /></a></div>
									<div class="comment-box">
										<div class="comment-author meta"> 
											<strong>Kimberly C.</strong> said 1 month ago <a href="#" class="comment-reply-link"> Reply</a>
										</div>
										<div class="comment-text">
											<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>
										</div>
									</div> 
								</li>
								<!--//comment-->

								<!--comment-->
								<li class="comment depth-1">
									<div class="avatar"><a href="my_profile.html"><img src="/images/avatar2.jpg" alt="" /></a></div>
									<div class="comment-box">
										<div class="comment-author meta"> 
											<strong>Alex J.</strong> said 1 month ago <a href="#" class="comment-reply-link"> Reply</a>
										</div>
										<div class="comment-text">
											<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>
										</div>
									</div> 
								</li>
								<!--//comment-->

								<!--comment-->
								<li class="comment depth-2">
									<div class="avatar"><a href="my_profile.html"><img src="/images/avatar1.jpg" alt="" /></a></div>
									<div class="comment-box">
										<div class="comment-author meta"> 
											<strong>Kimberly C.</strong> said 1 month ago <a href="#" class="comment-reply-link"> Reply</a>
										</div>
										<div class="comment-text">
											<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>
										</div>
									</div> 
								</li>
								<!--//comment-->

								<!--comment-->
								<li class="comment depth-3">
									<div class="avatar"><a href="my_profile.html"><img src="/images/avatar2.jpg" alt="" /></a></div>
									<div class="comment-box">
										<div class="comment-author meta"> 
											<strong>Alex J.</strong> said 1 month ago <a href="#" class="comment-reply-link"> Reply</a>
										</div>
										<div class="comment-text">
											<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>
										</div>
									</div> 
								</li>
								<!--//comment-->

								<!--comment-->
								<li class="comment depth-1">
									<div class="avatar"><a href="my_profile.html"><img src="/images/avatar3.jpg" alt="" /></a></div>
									<div class="comment-box">
										<div class="comment-author meta"> 
											<strong>Denise M.</strong> said 1 month ago <a href="#" class="comment-reply-link"> Reply</a>
										</div>
										<div class="comment-text">
											<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>
										</div>
									</div> 
								</li>
								<!--//comment-->
							</ol>
						</div>
						<!--//comments-->

						<!--respond-->
						<div class="comment-respond wow fadeInUp" id="respond">
							<h2>Leave a reply</h2>
							<div class="container">
								<p><strong>Note:</strong> Comments on the web site reflect the views of their authors, and not necessarily the views of the socialchef internet portal. Requested to refrain from insults, swearing and vulgar expression. We reserve the right to delete any comment without notice explanations.</p>
								<p>Your email address will not be published. Required fields are signed with <span class="req">*</span></p>
								<form>
									<div class="f-row">
										<div class="third">
											<input type="text" placeholder="Your name" />
											<span class="req">*</span>
										</div>

										<div class="third">
											<input type="email" placeholder="Your email" />
											<span class="req">*</span>
										</div>

										<div class="third">
											<input type="text" placeholder="Your website" />
										</div>

									</div>
									<div class="f-row">
										<textarea></textarea>
									</div>

									<div class="f-row">
										<div class="third bwrap">
											<input type="submit" value="Submit comment" />
										</div>
									</div>

									<div class="bottom">
										<div class="f-row checkbox">
											<input type="checkbox" id="ch1" />
											<label for="ch1">Notify me of replies to my comment via e-mail</label>
										</div>
										<div class="f-row checkbox">
											<input type="checkbox" id="ch2" />
											<label for="ch2">Notify me of new articles by email.</label>
										</div>
									</div>
								</form>
							</div>
						</div>
						<!--//respond-->
				</section>
				<!--//content-->

				<!--right sidebar-->
				<aside class="sidebar one-fourth wow fadeInRight">
					<div class="widget nutrition">
						<h3>Nutrition facts <span>(per serving)</span></h3>
						<table>
							<tr>
								<td>Calories </td>
								<td>505</td>
							</tr>
							<tr>
								<td>Protein</td>
								<td>59g</td>
							</tr>
							<tr>
								<td>Carbs</td>
								<td>59g</td>
							</tr>
							<tr>
								<td>Fat</td>
								<td>29g</td>
							</tr>
							<tr>
								<td>Saturates</td>
								<td>17g</td>
							</tr>
							<tr>
								<td>Fibre</td>
								<td>2g</td>
							</tr>
							<tr>
								<td>Sugar</td>
								<td>44g</td>
							</tr>
							<tr>
								<td>Salt</td>
								<td>0.51g</td>
							</tr>
						</table>
					</div>

					<div class="widget share">
						<ul class="boxed">
							<li class="light"><a href="#" title="Facebook"><i class="ico i-facebook"></i> <span>Share on Facebook</span></a></li>
							<li class="medium"><a href="#" title="Twitter"><i class="ico i-twitter"></i> <span>Share on Twitter</span></a></li>
							<li class="dark"><a href="#" title="Favourites"><i class="ico i-favourites"></i> <span>Add to Favourites</span></a></li>
						</ul>
					</div>

					<div class="widget members">
						<h3>Members who liked this recipe</h3>
						<ul class="boxed">
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar1.jpg" alt="" /><span>Kimberly C.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar2.jpg" alt="" /><span>Alex J.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar3.jpg" alt="" /><span>Denise M.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar9.jpg" alt="" /><span>Jason H.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar8.jpg" alt="" /><span>Jennifer W.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar4.jpg" alt="" /><span>Anabelle Q.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar7.jpg" alt="" /><span>Thomas M.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar5.jpg" alt="" /><span>Michelle S.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="/images/avatar6.jpg" alt="" /><span>Bryan A.</span></a></div></li>
						</ul>
					</div>
				</aside>
				<!--//right sidebar-->
			</div>
			<!--//row-->
		</div>
		<!--//wrap-->
	</main>

app/views/user_contact/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Contact</title>
</head>
<body>
	<h1>Xin chào bạn <%= @name %>,</h1>
	<h1>Phone: <%= @phone %> </h1>
	<h1>Email: <%= @email %></h1>
	<p>
		<%= @comments %>
	</p>
</body>
</html>

app/views/users/login_form.html.erb
		
	<!--main-->
	<main class="main" role="main">
		<!--wrap-->
		<div class="wrap clearfix">
			<!--row-->
			<div class="row">
			<!--content-->
				<section class="content center full-width wow fadeInUp">
					<div class="modal container">
						<h3>Login</h3>
						<form action="/users/login" method="POST">
							<div class="f-row">
								<input type="email" name="user[email]" placeholder="Your email" />
							</div>
							<div class="f-row">
								<input type="password" name="user[password]" placeholder="Your password" />
							</div>
							<div class="f-row">
								<input type="checkbox" />
								<label>Remember me next time</label>
							</div>
							<div class="f-row bwrap">
								<input type="submit" value="login" />
							</div>
						</form>
						<p><a href="#">Forgotten password?</a></p>
						<p>Dont have an account yet? <a href="/users/register">Sign up.</a></p>
					</div>
				</section>
				<!--//content-->
			</div>
			<!--//row-->
		</div>
		<!--//wrap-->
	</main>
	<!--//main-->

app/views/users/register_form.html.erb
	<!--main-->
	<main class="main" role="main">
		<!--wrap-->
		<div class="wrap clearfix">
			<!--row-->
			<div class="row">
			<!--content-->
				<section class="content center full-width wow fadeInUp">
					<div class="modal container">
						<h3>Register</h3>
						<form action="/users/register" method="POST">
							<div class="f-row">
								<input type="text" name="user[name]" placeholder="Your name" />
							</div>
							<div class="f-row">
								<input type="email" name="user[email]" placeholder="Your email" />
							</div>
							<div class="f-row">
								<input type="password" name="user[password]" placeholder="Your password" />
							</div>
							<div class="f-row">
								<input type="password" name="user[confirm_password]" placeholder="Retype password" />
							</div>
							<div class="f-row bwrap">
								<input type="submit" value="register" />
							</div>
						</form>
						<p>Already have an account yet? <a href="/users/login">Log in.</a></p>
					</div>
				</section>
				<!--//content-->
			</div>
			<!--//row-->
		</div>
		<!--//wrap-->
	</main>
	<!--//main-->